package com.nursery_school.manager.mapper;

import com.nursery_school.manager.model.ActivityStudent;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ActivityStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Delete({
        "delete from t_activity_student",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Insert({
        "insert into t_activity_student (id, activity_id, ",
        "staff_id, student_id, ",
        "ac_date)",
        "values (#{id,jdbcType=VARCHAR}, #{activityId,jdbcType=VARCHAR}, ",
        "#{staffId,jdbcType=VARCHAR}, #{studentId,jdbcType=VARCHAR}, ",
        "#{acDate,jdbcType=TIMESTAMP})"
    })
    int insert(ActivityStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Select({
        "select",
        "id, activity_id, staff_id, student_id, ac_date",
        "from t_activity_student",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.VARCHAR),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="ac_date", property="acDate", jdbcType=JdbcType.TIMESTAMP)
    })
    ActivityStudent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Select({
        "select",
        "id, activity_id, staff_id, student_id, ac_date",
        "from t_activity_student"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.VARCHAR),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="ac_date", property="acDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ActivityStudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Update({
        "update t_activity_student",
        "set activity_id = #{activityId,jdbcType=VARCHAR},",
          "staff_id = #{staffId,jdbcType=VARCHAR},",
          "student_id = #{studentId,jdbcType=VARCHAR},",
          "ac_date = #{acDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ActivityStudent record);
    
    @SelectProvider(type = com.nursery_school.manager.model.dyna.ActivityStudentDynaProvider.class, method = "selectProvider")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="activity_id", property="activityId", jdbcType=JdbcType.VARCHAR),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="ac_date", property="acDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ActivityStudent> findByDyna(Map<String, Object> map);
//    
//    @UpdateProvider(type = com.nursery_school.manager.model.dyna.ActivityStudentDynaProvider.class, method = "updateProvider")
//    void updateProvider(Map<String, Object> map);
}