package com.nursery_school.manager.mapper;

import com.nursery_school.manager.model.Dishes;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface DishesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dishes
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    @Delete({
        "delete from t_dishes",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dishes
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    @Insert({
        "insert into t_dishes (id, name, ",
        "ingredients)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{ingredients,jdbcType=VARCHAR})"
    })
    int insert(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dishes
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    @Select({
        "select",
        "id, name, ingredients",
        "from t_dishes",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ingredients", property="ingredients", jdbcType=JdbcType.VARCHAR)
    })
    Dishes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dishes
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    @Select({
        "select",
        "id, name, ingredients",
        "from t_dishes"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ingredients", property="ingredients", jdbcType=JdbcType.VARCHAR)
    })
    List<Dishes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dishes
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    @Update({
        "update t_dishes",
        "set name = #{name,jdbcType=VARCHAR},",
          "ingredients = #{ingredients,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Dishes record);
    
    
    @SelectProvider(type = com.nursery_school.manager.model.dyna.DishesDynaProvider.class, method = "selectProvider")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="ingredients", property="ingredients", jdbcType=JdbcType.VARCHAR)
    })
    List<Dishes> findByDyna(Map<String, Object> map);
    
    @UpdateProvider(type = com.nursery_school.manager.model.dyna.DishesDynaProvider.class, method = "updateProvider")
    void updateProvider(Map<String, Object> map);
}