package com.nursery_school.manager.mapper;

import com.nursery_school.manager.model.Order;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    @Delete({
        "delete from t_order",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    @Insert({
        "insert into t_order (id, state, ",
        "parent_id, create_date, ",
        "pay_money, pay_mode, ",
        "pay_standard_id, student_id)",
        "values (#{id,jdbcType=VARCHAR}, #{state,jdbcType=INTEGER}, ",
        "#{parentId,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{payMoney,jdbcType=INTEGER}, #{payMode,jdbcType=VARCHAR}, ",
        "#{payStandardId,jdbcType=VARCHAR}, #{studentId,jdbcType=VARCHAR})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    @Select({
        "select",
        "id, state, parent_id, create_date, pay_money, pay_mode, pay_standard_id, student_id",
        "from t_order",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="pay_money", property="payMoney", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_mode", property="payMode", jdbcType=JdbcType.VARCHAR),
        @Result(column="pay_standard_id", property="payStandardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR)
    })
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    @Select({
        "select",
        "id, state, parent_id, create_date, pay_money, pay_mode, pay_standard_id, student_id",
        "from t_order"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="pay_money", property="payMoney", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_mode", property="payMode", jdbcType=JdbcType.VARCHAR),
        @Result(column="pay_standard_id", property="payStandardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR)
    })
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    @Update({
        "update t_order",
        "set state = #{state,jdbcType=INTEGER},",
          "parent_id = #{parentId,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "pay_money = #{payMoney,jdbcType=INTEGER},",
          "pay_mode = #{payMode,jdbcType=VARCHAR},",
          "pay_standard_id = #{payStandardId,jdbcType=VARCHAR},",
          "student_id = #{studentId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Order record);
    
    @SelectProvider(type = com.nursery_school.manager.model.dyna.OrderDynaProvider.class, method = "selectProvider")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="pay_money", property="payMoney", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_mode", property="payMode", jdbcType=JdbcType.VARCHAR),
        @Result(column="pay_standard_id", property="payStandardId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR)
    })
    List<Order> findByDyna(Map<String, Object> map);
}