package com.nursery_school.manager.mapper;

import com.nursery_school.manager.model.ProjectStudent;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ProjectStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Delete({
        "delete from t_project_student",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Insert({
        "insert into t_project_student (id, project_id, ",
        "student_id, teacher_id)",
        "values (#{id,jdbcType=VARCHAR}, #{projectId,jdbcType=VARCHAR}, ",
        "#{studentId,jdbcType=VARCHAR}, #{teacherId,jdbcType=VARCHAR})"
    })
    int insert(ProjectStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Select({
        "select",
        "id, project_id, student_id, teacher_id",
        "from t_project_student",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="project_id", property="projectId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="teacher_id", property="teacherId", jdbcType=JdbcType.VARCHAR)
    })
    ProjectStudent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Select({
        "select",
        "id, project_id, student_id, teacher_id",
        "from t_project_student"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="project_id", property="projectId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="teacher_id", property="teacherId", jdbcType=JdbcType.VARCHAR)
    })
    List<ProjectStudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_student
     *
     * @mbg.generated Tue Nov 26 20:23:43 CST 2019
     */
    @Update({
        "update t_project_student",
        "set project_id = #{projectId,jdbcType=VARCHAR},",
          "student_id = #{studentId,jdbcType=VARCHAR},",
          "teacher_id = #{teacherId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ProjectStudent record);
    
    @SelectProvider(type = com.nursery_school.manager.model.dyna.ProjectStudentDynaProvider.class, method = "selectProvider")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="project_id", property="projectId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="teacher_id", property="teacherId", jdbcType=JdbcType.VARCHAR)
    })
    List<ProjectStudent> findByDyna(Map<String, Object> map);
}