package com.nursery_school.manager.mapper;

import com.nursery_school.manager.model.Student;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sat Sep 28 15:39:12 CST 2019
     */
    @Delete({
        "delete from t_student",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sat Sep 28 15:39:12 CST 2019
     */
    @Insert({
        "insert into t_student (id, name, ",
        "contract, address, ",
        "in_date, parent_id, student_id, ",
        "father_tel, mather_tel, ",
        "father_name, mather_name, ",
        "birthday, gender, class_id)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{contract,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{inDate,jdbcType=DATE}, #{parentId,jdbcType=VARCHAR}, #{studentId,jdbcType=VARCHAR}, ",
        "#{fatherTel,jdbcType=VARCHAR}, #{matherTel,jdbcType=VARCHAR}, ",
        "#{fatherName,jdbcType=VARCHAR}, #{matherName,jdbcType=VARCHAR}, ",
        "#{birthday,jdbcType=DATE}, #{gender,jdbcType=INTEGER}, #{classId,jdbcType=VARCHAR})"
    })
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sat Sep 28 15:39:12 CST 2019
     */
    @Select({
        "select",
        "id, name, contract, address, in_date, parent_id, student_id, father_tel, mather_tel, ",
        "father_name, mather_name, birthday, gender, class_id",
        "from t_student",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="contract", property="contract", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_date", property="inDate", jdbcType=JdbcType.DATE),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="father_tel", property="fatherTel", jdbcType=JdbcType.VARCHAR),
        @Result(column="mather_tel", property="matherTel", jdbcType=JdbcType.VARCHAR),
        @Result(column="father_name", property="fatherName", jdbcType=JdbcType.VARCHAR),
        @Result(column="mather_name", property="matherName", jdbcType=JdbcType.VARCHAR),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.DATE),
        @Result(column="gender", property="gender", jdbcType=JdbcType.INTEGER),
        @Result(column="class_id", property="classId", jdbcType=JdbcType.VARCHAR)
    })
    Student selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sat Sep 28 15:39:12 CST 2019
     */
    @Select({
        "select",
        "id, name, contract, address, in_date, parent_id, student_id, father_tel, mather_tel, ",
        "father_name, mather_name, birthday, gender, class_id",
        "from t_student"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="contract", property="contract", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_date", property="inDate", jdbcType=JdbcType.DATE),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="father_tel", property="fatherTel", jdbcType=JdbcType.VARCHAR),
        @Result(column="mather_tel", property="matherTel", jdbcType=JdbcType.VARCHAR),
        @Result(column="father_name", property="fatherName", jdbcType=JdbcType.VARCHAR),
        @Result(column="mather_name", property="matherName", jdbcType=JdbcType.VARCHAR),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.DATE),
        @Result(column="gender", property="gender", jdbcType=JdbcType.INTEGER),
        @Result(column="class_id", property="classId", jdbcType=JdbcType.VARCHAR)
    })
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sat Sep 28 15:39:12 CST 2019
     */
    @Update({
        "update t_student",
        "set name = #{name,jdbcType=VARCHAR},",
          "contract = #{contract,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "in_date = #{inDate,jdbcType=DATE},",
          "parent_id = #{parentId,jdbcType=VARCHAR},",
          "student_id = #{studentId,jdbcType=VARCHAR},",
          "father_tel = #{fatherTel,jdbcType=VARCHAR},",
          "mather_tel = #{matherTel,jdbcType=VARCHAR},",
          "father_name = #{fatherName,jdbcType=VARCHAR},",
          "mather_name = #{matherName,jdbcType=VARCHAR},",
          "birthday = #{birthday,jdbcType=DATE},",
          "gender = #{gender,jdbcType=INTEGER},",
          "class_id = #{classId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Student record);
    
    @SelectProvider(type = com.nursery_school.manager.model.dyna.StudentDynaProvider.class, method = "selectProvider")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="contract", property="contract", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_date", property="inDate", jdbcType=JdbcType.DATE),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="student_id", property="studentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="father_tel", property="fatherTel", jdbcType=JdbcType.VARCHAR),
        @Result(column="mather_tel", property="matherTel", jdbcType=JdbcType.VARCHAR),
        @Result(column="father_name", property="fatherName", jdbcType=JdbcType.VARCHAR),
        @Result(column="mather_name", property="matherName", jdbcType=JdbcType.VARCHAR),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.DATE),
        @Result(column="gender", property="gender", jdbcType=JdbcType.INTEGER),
        @Result(column="class_id", property="classId", jdbcType=JdbcType.VARCHAR)
    })
    List<Student> findDyna(Map<String, Object> map);
    
    @UpdateProvider(type = com.nursery_school.manager.model.dyna.StudentDynaProvider.class, method = "updateProvider")
    void updateProvider(Map<String, Object> map);
}