package com.nursery_school.manager.model;

import java.util.Date;

import org.springframework.data.annotation.Transient;

public class ActivityStudent {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_activity_student.id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_activity_student.activity_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private String activityId;

	@Transient
	private Activity activity;
	@Transient
	private Staff staff;
	@Transient
	private Student student;

	public Activity getActivity() {
		return activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public Staff getStaff() {
		return staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_activity_student.staff_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private String staffId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_activity_student.student_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private String studentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_activity_student.ac_date
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private Date acDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_activity_student.id
	 *
	 * @return the value of t_activity_student.id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_activity_student.id
	 *
	 * @param id
	 *            the value for t_activity_student.id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_activity_student.activity_id
	 *
	 * @return the value of t_activity_student.activity_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public String getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_activity_student.activity_id
	 *
	 * @param activityId
	 *            the value for t_activity_student.activity_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setActivityId(String activityId) {
		this.activityId = activityId == null ? null : activityId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_activity_student.staff_id
	 *
	 * @return the value of t_activity_student.staff_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public String getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_activity_student.staff_id
	 *
	 * @param staffId
	 *            the value for t_activity_student.staff_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setStaffId(String staffId) {
		this.staffId = staffId == null ? null : staffId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_activity_student.student_id
	 *
	 * @return the value of t_activity_student.student_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public String getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_activity_student.student_id
	 *
	 * @param studentId
	 *            the value for t_activity_student.student_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setStudentId(String studentId) {
		this.studentId = studentId == null ? null : studentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_activity_student.ac_date
	 *
	 * @return the value of t_activity_student.ac_date
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public Date getAcDate() {
		return acDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_activity_student.ac_date
	 *
	 * @param acDate
	 *            the value for t_activity_student.ac_date
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setAcDate(Date acDate) {
		this.acDate = acDate;
	}
}