package com.nursery_school.manager.model;

import java.util.Date;

import org.springframework.data.annotation.Transient;

public class CleaningInfo {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cleaning_info.id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cleaning_info.cleaning_id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	private String cleaningId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cleaning_info.clean_start_time
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	private Date cleanStartTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cleaning_info.clean_end_time
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	private Date cleanEndTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cleaning_info.staff_id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	private String staffId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cleaning_info.img
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	private String img;

	@Transient
	private Staff staff;
	@Transient
	private Cleaning cleaning;

	public Staff getStaff() {
		return staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Cleaning getCleaning() {
		return cleaning;
	}

	public void setCleaning(Cleaning cleaning) {
		this.cleaning = cleaning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_cleaning_info.id
	 *
	 * @return the value of t_cleaning_info.id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_cleaning_info.id
	 *
	 * @param id
	 *            the value for t_cleaning_info.id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_cleaning_info.cleaning_id
	 *
	 * @return the value of t_cleaning_info.cleaning_id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public String getCleaningId() {
		return cleaningId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_cleaning_info.cleaning_id
	 *
	 * @param cleaningId
	 *            the value for t_cleaning_info.cleaning_id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public void setCleaningId(String cleaningId) {
		this.cleaningId = cleaningId == null ? null : cleaningId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_cleaning_info.clean_start_time
	 *
	 * @return the value of t_cleaning_info.clean_start_time
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public Date getCleanStartTime() {
		return cleanStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_cleaning_info.clean_start_time
	 *
	 * @param cleanStartTime
	 *            the value for t_cleaning_info.clean_start_time
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public void setCleanStartTime(Date cleanStartTime) {
		this.cleanStartTime = cleanStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_cleaning_info.clean_end_time
	 *
	 * @return the value of t_cleaning_info.clean_end_time
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public Date getCleanEndTime() {
		return cleanEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_cleaning_info.clean_end_time
	 *
	 * @param cleanEndTime
	 *            the value for t_cleaning_info.clean_end_time
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public void setCleanEndTime(Date cleanEndTime) {
		this.cleanEndTime = cleanEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_cleaning_info.staff_id
	 *
	 * @return the value of t_cleaning_info.staff_id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public String getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_cleaning_info.staff_id
	 *
	 * @param staffId
	 *            the value for t_cleaning_info.staff_id
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public void setStaffId(String staffId) {
		this.staffId = staffId == null ? null : staffId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_cleaning_info.img
	 *
	 * @return the value of t_cleaning_info.img
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_cleaning_info.img
	 *
	 * @param img
	 *            the value for t_cleaning_info.img
	 *
	 * @mbg.generated Wed Oct 02 19:06:01 CST 2019
	 */
	public void setImg(String img) {
		this.img = img == null ? null : img.trim();
	}
}