package com.nursery_school.manager.model;

public class Cleaning {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cleaning.id
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cleaning.site
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    private String site;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cleaning.content
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cleaning.period
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cleaning.standard
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    private String standard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cleaning.time
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cleaning.id
     *
     * @return the value of t_cleaning.id
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cleaning.id
     *
     * @param id the value for t_cleaning.id
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cleaning.site
     *
     * @return the value of t_cleaning.site
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cleaning.site
     *
     * @param site the value for t_cleaning.site
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cleaning.content
     *
     * @return the value of t_cleaning.content
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cleaning.content
     *
     * @param content the value for t_cleaning.content
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cleaning.period
     *
     * @return the value of t_cleaning.period
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cleaning.period
     *
     * @param period the value for t_cleaning.period
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cleaning.standard
     *
     * @return the value of t_cleaning.standard
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cleaning.standard
     *
     * @param standard the value for t_cleaning.standard
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cleaning.time
     *
     * @return the value of t_cleaning.time
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cleaning.time
     *
     * @param time the value for t_cleaning.time
     *
     * @mbg.generated Wed Oct 02 19:06:01 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}