package com.nursery_school.manager.model;

import java.util.Date;

import org.springframework.data.annotation.Transient;

public class Communication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communication.id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communication.title
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communication.content
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communication.create_date
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communication.user_id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communication.to_user_id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    private String toUserId;
    
    @Transient
    private User toUser;
    
    @Transient
    private User user;
    
    public User getToUser() {
		return toUser;
	}

	public void setToUser(User toUser) {
		this.toUser = toUser;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communication.id
     *
     * @return the value of t_communication.id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communication.id
     *
     * @param id the value for t_communication.id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communication.title
     *
     * @return the value of t_communication.title
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communication.title
     *
     * @param title the value for t_communication.title
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communication.content
     *
     * @return the value of t_communication.content
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communication.content
     *
     * @param content the value for t_communication.content
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communication.create_date
     *
     * @return the value of t_communication.create_date
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communication.create_date
     *
     * @param createDate the value for t_communication.create_date
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communication.user_id
     *
     * @return the value of t_communication.user_id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communication.user_id
     *
     * @param userId the value for t_communication.user_id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communication.to_user_id
     *
     * @return the value of t_communication.to_user_id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communication.to_user_id
     *
     * @param toUserId the value for t_communication.to_user_id
     *
     * @mbg.generated Thu Oct 03 17:33:18 CST 2019
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId == null ? null : toUserId.trim();
    }
}