package com.nursery_school.manager.model;

public class Dishes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dishes.id
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dishes.name
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dishes.ingredients
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    private String ingredients;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dishes.id
     *
     * @return the value of t_dishes.id
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dishes.id
     *
     * @param id the value for t_dishes.id
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dishes.name
     *
     * @return the value of t_dishes.name
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dishes.name
     *
     * @param name the value for t_dishes.name
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dishes.ingredients
     *
     * @return the value of t_dishes.ingredients
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    public String getIngredients() {
        return ingredients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dishes.ingredients
     *
     * @param ingredients the value for t_dishes.ingredients
     *
     * @mbg.generated Sun Oct 06 15:27:52 CST 2019
     */
    public void setIngredients(String ingredients) {
        this.ingredients = ingredients == null ? null : ingredients.trim();
    }
}