package com.nursery_school.manager.model;

import java.util.Date;
import java.util.List;

import org.springframework.data.annotation.Transient;

public class DishesDaily {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.breakfast_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private String breakfastFood;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.breakfast_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private Integer breakfastMoney;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.lunch_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private String lunchFood;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.lunch_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private Integer lunchMoney;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.dinner_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private String dinnerFood;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.dinner_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private Integer dinnerMoney;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.dishes_date
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private Date dishesDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.create_date
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private Date createDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.create_by
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private String createBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.breakfast_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private String breakfastFoodId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.lunch_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private String lunchFoodId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_dishes_daily.dinner_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	private String dinnerFoodId;

	@Transient
	private List<Dishes> breakfastDishes;
	@Transient
	private List<Dishes> lunchDishes;
	@Transient
	private List<Dishes> dinnerDishes;

	public List<Dishes> getBreakfastDishes() {
		return breakfastDishes;
	}

	public void setBreakfastDishes(List<Dishes> breakfastDishes) {
		this.breakfastDishes = breakfastDishes;
	}

	public List<Dishes> getLunchDishes() {
		return lunchDishes;
	}

	public void setLunchDishes(List<Dishes> lunchDishes) {
		this.lunchDishes = lunchDishes;
	}

	public List<Dishes> getDinnerDishes() {
		return dinnerDishes;
	}

	public void setDinnerDishes(List<Dishes> dinnerDishes) {
		this.dinnerDishes = dinnerDishes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.id
	 *
	 * @return the value of t_dishes_daily.id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.id
	 *
	 * @param id
	 *            the value for t_dishes_daily.id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.breakfast_food
	 *
	 * @return the value of t_dishes_daily.breakfast_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public String getBreakfastFood() {
		return breakfastFood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.breakfast_food
	 *
	 * @param breakfastFood
	 *            the value for t_dishes_daily.breakfast_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setBreakfastFood(String breakfastFood) {
		this.breakfastFood = breakfastFood == null ? null : breakfastFood.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.breakfast_money
	 *
	 * @return the value of t_dishes_daily.breakfast_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public Integer getBreakfastMoney() {
		return breakfastMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.breakfast_money
	 *
	 * @param breakfastMoney
	 *            the value for t_dishes_daily.breakfast_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setBreakfastMoney(Integer breakfastMoney) {
		this.breakfastMoney = breakfastMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.lunch_food
	 *
	 * @return the value of t_dishes_daily.lunch_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public String getLunchFood() {
		return lunchFood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.lunch_food
	 *
	 * @param lunchFood
	 *            the value for t_dishes_daily.lunch_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setLunchFood(String lunchFood) {
		this.lunchFood = lunchFood == null ? null : lunchFood.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.lunch_money
	 *
	 * @return the value of t_dishes_daily.lunch_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public Integer getLunchMoney() {
		return lunchMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.lunch_money
	 *
	 * @param lunchMoney
	 *            the value for t_dishes_daily.lunch_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setLunchMoney(Integer lunchMoney) {
		this.lunchMoney = lunchMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.dinner_food
	 *
	 * @return the value of t_dishes_daily.dinner_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public String getDinnerFood() {
		return dinnerFood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.dinner_food
	 *
	 * @param dinnerFood
	 *            the value for t_dishes_daily.dinner_food
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setDinnerFood(String dinnerFood) {
		this.dinnerFood = dinnerFood == null ? null : dinnerFood.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.dinner_money
	 *
	 * @return the value of t_dishes_daily.dinner_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public Integer getDinnerMoney() {
		return dinnerMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.dinner_money
	 *
	 * @param dinnerMoney
	 *            the value for t_dishes_daily.dinner_money
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setDinnerMoney(Integer dinnerMoney) {
		this.dinnerMoney = dinnerMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.dishes_date
	 *
	 * @return the value of t_dishes_daily.dishes_date
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public Date getDishesDate() {
		return dishesDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.dishes_date
	 *
	 * @param dishesDate
	 *            the value for t_dishes_daily.dishes_date
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setDishesDate(Date dishesDate) {
		this.dishesDate = dishesDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.create_date
	 *
	 * @return the value of t_dishes_daily.create_date
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.create_date
	 *
	 * @param createDate
	 *            the value for t_dishes_daily.create_date
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.create_by
	 *
	 * @return the value of t_dishes_daily.create_by
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.create_by
	 *
	 * @param createBy
	 *            the value for t_dishes_daily.create_by
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.breakfast_food_id
	 *
	 * @return the value of t_dishes_daily.breakfast_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public String getBreakfastFoodId() {
		return breakfastFoodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.breakfast_food_id
	 *
	 * @param breakfastFoodId
	 *            the value for t_dishes_daily.breakfast_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setBreakfastFoodId(String breakfastFoodId) {
		this.breakfastFoodId = breakfastFoodId == null ? null : breakfastFoodId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.lunch_food_id
	 *
	 * @return the value of t_dishes_daily.lunch_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public String getLunchFoodId() {
		return lunchFoodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.lunch_food_id
	 *
	 * @param lunchFoodId
	 *            the value for t_dishes_daily.lunch_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setLunchFoodId(String lunchFoodId) {
		this.lunchFoodId = lunchFoodId == null ? null : lunchFoodId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_dishes_daily.dinner_food_id
	 *
	 * @return the value of t_dishes_daily.dinner_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public String getDinnerFoodId() {
		return dinnerFoodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_dishes_daily.dinner_food_id
	 *
	 * @param dinnerFoodId
	 *            the value for t_dishes_daily.dinner_food_id
	 *
	 * @mbg.generated Sun Oct 06 17:41:49 CST 2019
	 */
	public void setDinnerFoodId(String dinnerFoodId) {
		this.dinnerFoodId = dinnerFoodId == null ? null : dinnerFoodId.trim();
	}
}