package com.nursery_school.manager.model;

import java.util.Date;

import org.springframework.data.annotation.Transient;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.state
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.parent_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_date
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_money
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    private Integer payMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_mode
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    private String payMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_standard_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    private String payStandardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.student_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    private String studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public String getId() {
        return id;
    }

    @Transient
    private PayStandard payStandard;
    
    public PayStandard getPayStandard() {
		return payStandard;
	}

	public void setPayStandard(PayStandard payStandard) {
		this.payStandard = payStandard;
	}

    @Transient
    private Student student;
    
	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}
	
	 @Transient
	 private Parents parents;

	public Parents getParents() {
		return parents;
	}

	public void setParents(Parents parents) {
		this.parents = parents;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.state
     *
     * @return the value of t_order.state
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.state
     *
     * @param state the value for t_order.state
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.parent_id
     *
     * @return the value of t_order.parent_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.parent_id
     *
     * @param parentId the value for t_order.parent_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_date
     *
     * @return the value of t_order.create_date
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_date
     *
     * @param createDate the value for t_order.create_date
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_money
     *
     * @return the value of t_order.pay_money
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public Integer getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_money
     *
     * @param payMoney the value for t_order.pay_money
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public void setPayMoney(Integer payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_mode
     *
     * @return the value of t_order.pay_mode
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public String getPayMode() {
        return payMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_mode
     *
     * @param payMode the value for t_order.pay_mode
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public void setPayMode(String payMode) {
        this.payMode = payMode == null ? null : payMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_standard_id
     *
     * @return the value of t_order.pay_standard_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public String getPayStandardId() {
        return payStandardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_standard_id
     *
     * @param payStandardId the value for t_order.pay_standard_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public void setPayStandardId(String payStandardId) {
        this.payStandardId = payStandardId == null ? null : payStandardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.student_id
     *
     * @return the value of t_order.student_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.student_id
     *
     * @param studentId the value for t_order.student_id
     *
     * @mbg.generated Mon Sep 30 20:05:55 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }
}