package com.nursery_school.manager.model;

public class Parents {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.id
     *
     * @mbg.generated Sat Sep 28 15:40:00 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.name
     *
     * @mbg.generated Sat Sep 28 15:40:00 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.id
     *
     * @return the value of t_parents.id
     *
     * @mbg.generated Sat Sep 28 15:40:00 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.id
     *
     * @param id the value for t_parents.id
     *
     * @mbg.generated Sat Sep 28 15:40:00 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.name
     *
     * @return the value of t_parents.name
     *
     * @mbg.generated Sat Sep 28 15:40:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.name
     *
     * @param name the value for t_parents.name
     *
     * @mbg.generated Sat Sep 28 15:40:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}