package com.nursery_school.manager.model;

import java.util.Date;

public class PayStandard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_standard.id
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_standard.schooling
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    private Integer schooling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_standard.book_money
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    private Integer bookMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_standard.board_ages
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    private Integer boardAges;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_standard.quarterage
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    private Integer quarterage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_standard.payment_deadline
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    private Date paymentDeadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_standard.year
     *
     * @mbg.generated Thu Oct 10 19:53:04 CST 2019
     */
    private Date year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_standard.file
     *
     * @mbg.generated Thu Oct 10 19:53:04 CST 2019
     */
    private String file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_standard.id
     *
     * @return the value of t_pay_standard.id
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_standard.id
     *
     * @param id the value for t_pay_standard.id
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_standard.schooling
     *
     * @return the value of t_pay_standard.schooling
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public Integer getSchooling() {
        return schooling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_standard.schooling
     *
     * @param schooling the value for t_pay_standard.schooling
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public void setSchooling(Integer schooling) {
        this.schooling = schooling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_standard.book_money
     *
     * @return the value of t_pay_standard.book_money
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public Integer getBookMoney() {
        return bookMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_standard.book_money
     *
     * @param bookMoney the value for t_pay_standard.book_money
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public void setBookMoney(Integer bookMoney) {
        this.bookMoney = bookMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_standard.board_ages
     *
     * @return the value of t_pay_standard.board_ages
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public Integer getBoardAges() {
        return boardAges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_standard.board_ages
     *
     * @param boardAges the value for t_pay_standard.board_ages
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public void setBoardAges(Integer boardAges) {
        this.boardAges = boardAges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_standard.quarterage
     *
     * @return the value of t_pay_standard.quarterage
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public Integer getQuarterage() {
        return quarterage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_standard.quarterage
     *
     * @param quarterage the value for t_pay_standard.quarterage
     *
     * @mbg.generated Thu Oct 10 19:53:03 CST 2019
     */
    public void setQuarterage(Integer quarterage) {
        this.quarterage = quarterage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_standard.payment_deadline
     *
     * @return the value of t_pay_standard.payment_deadline
     *
     * @mbg.generated Thu Oct 10 19:53:04 CST 2019
     */
    public Date getPaymentDeadline() {
        return paymentDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_standard.payment_deadline
     *
     * @param paymentDeadline the value for t_pay_standard.payment_deadline
     *
     * @mbg.generated Thu Oct 10 19:53:04 CST 2019
     */
    public void setPaymentDeadline(Date paymentDeadline) {
        this.paymentDeadline = paymentDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_standard.year
     *
     * @return the value of t_pay_standard.year
     *
     * @mbg.generated Thu Oct 10 19:53:04 CST 2019
     */
    public Date getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_standard.year
     *
     * @param year the value for t_pay_standard.year
     *
     * @mbg.generated Thu Oct 10 19:53:04 CST 2019
     */
    public void setYear(Date year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_standard.file
     *
     * @return the value of t_pay_standard.file
     *
     * @mbg.generated Thu Oct 10 19:53:04 CST 2019
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_standard.file
     *
     * @param file the value for t_pay_standard.file
     *
     * @mbg.generated Thu Oct 10 19:53:04 CST 2019
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }
}