package com.nursery_school.manager.model;

import org.springframework.data.annotation.Transient;

public class ProjectStudent {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_project_student.id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_project_student.project_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private String projectId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_project_student.student_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private String studentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_project_student.teacher_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	private String teacherId;

	@Transient
	private Project project;
	@Transient
	private Staff staff;
	@Transient
	private Student student;

	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Staff getStaff() {
		return staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_project_student.id
	 *
	 * @return the value of t_project_student.id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_project_student.id
	 *
	 * @param id
	 *            the value for t_project_student.id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_project_student.project_id
	 *
	 * @return the value of t_project_student.project_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public String getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_project_student.project_id
	 *
	 * @param projectId
	 *            the value for t_project_student.project_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId == null ? null : projectId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_project_student.student_id
	 *
	 * @return the value of t_project_student.student_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public String getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_project_student.student_id
	 *
	 * @param studentId
	 *            the value for t_project_student.student_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setStudentId(String studentId) {
		this.studentId = studentId == null ? null : studentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_project_student.teacher_id
	 *
	 * @return the value of t_project_student.teacher_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public String getTeacherId() {
		return teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_project_student.teacher_id
	 *
	 * @param teacherId
	 *            the value for t_project_student.teacher_id
	 *
	 * @mbg.generated Tue Nov 26 20:23:43 CST 2019
	 */
	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId == null ? null : teacherId.trim();
	}
}